FROM composer:latest as composer
FROM php:7.3.5-apache

ENV OPCACHE_FILE=$PHP_INI_DIR/conf.d/opcache.ini

WORKDIR /var/www/
ADD . /var/www/

RUN apt-get update && apt-get install -y git zip unzip libpq-dev
RUN docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql
RUN docker-php-ext-install pgsql pdo_pgsql

COPY --from=composer /usr/bin/composer /usr/bin/composer
RUN composer install

ARG XDEBUG_REMOTE_HOST=docker.for.mac.localhost
ENV XDEBUG_CONFIGURATION_FILE='/usr/local/etc/php/conf.d/xdebug.ini'
ENV OPCACHE_FILE=$PHP_INI_DIR/conf.d/opcache.ini
ENV SITES_AVAILABLE=/etc/apache2/sites-available/app.conf

RUN yes | pecl install xdebug
RUN echo 'xdebug.idekey=PHPSTORM' >> $XDEBUG_CONFIGURATION_FILE && \
    echo 'xdebug.remote_enable=1' >> $XDEBUG_CONFIGURATION_FILE && \
    echo 'xdebug.remote_port=9090' >> $XDEBUG_CONFIGURATION_FILE && \
    echo 'xdebug.remote_connect_back=0' >> $XDEBUG_CONFIGURATION_FILE && \
    echo 'xdebug.remote_autostart=1' >> $XDEBUG_CONFIGURATION_FILE && \
    echo 'xdebug.remote_log="/var/log/xdebug/xdebug.log"' >> $XDEBUG_CONFIGURATION_FILE && \
    echo "xdebug.remote_host=$XDEBUG_REMOTE_HOST" >> $XDEBUG_CONFIGURATION_FILE && \
    echo ';;settings for profiling' >> $XDEBUG_CONFIGURATION_FILE && \
    echo 'xdebug.profiler_enable_trigger=1' >> $XDEBUG_CONFIGURATION_FILE && \
    echo 'xdebug.profiler_output_name=xdebug.out.%t' >> $XDEBUG_CONFIGURATION_FILE && \
    echo 'xdebug.profiler_output_dir="/tmp/xdebug"' >> $XDEBUG_CONFIGURATION_FILE && \
    echo 'xdebug.profiler_enable_trigger=1' >> $XDEBUG_CONFIGURATION_FILE && \
    echo 'xdebug.trace_enable_trigger=1' >> $XDEBUG_CONFIGURATION_FILE && \
    echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" >> $XDEBUG_CONFIGURATION_FILE

RUN echo '<VirtualHost *:80>' >> $SITES_AVAILABLE && \
    echo '  ServerName app' >> $SITES_AVAILABLE && \
    echo '  DocumentRoot /var/www/public' >> $SITES_AVAILABLE && \
    echo '  DirectoryIndex index.php index.html' >> $SITES_AVAILABLE && \
    echo '  <Directory /var/www/public>' >> $SITES_AVAILABLE && \
    echo '      Options Indexes FollowSymLinks' >> $SITES_AVAILABLE && \
    echo '      AllowOverride All' >> $SITES_AVAILABLE && \
    echo '      Order allow,deny' >> $SITES_AVAILABLE && \
    echo '      Allow from all' >> $SITES_AVAILABLE && \
    echo '  </Directory>' >> $SITES_AVAILABLE && \
    echo '</VirtualHost>' >> $SITES_AVAILABLE

RUN cd /etc/apache2/sites-available && a2dissite *
RUN cd /etc/apache2/sites-available && a2ensite app
RUN a2enmod rewrite

RUN mkdir /var/log/xdebug && chmod 0777 /var/log/xdebug
